# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           pretty

# Setup
title:               derzorngottes
tagline:             'AR/VR dev, thoughts on coding, culture & future'
description:         'A space for exploring ideas relating to AR/VR futurism, game development, and representation and culture in the industry'
url:                 http://derzorngottes.com
baseurl:             ''
paginate:            5

# About/contact
author:
<<<<<<< HEAD
  name:              derzorngottes
  url:               https://twitter.com/derzorngottes
  email:

# Custom vars
version:             1.0.0

plugins:
    [jekyll-paginate]
